name: Calendar Versioning

on:
  schedule:
    - cron: "30 23 * * 5"
  workflow_dispatch:

permissions:
  actions: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.11"
      - name: Check for new commits
        id: check
        run: |
          LAST_TAG=$(git tag --sort -v:refname | head -n1)
          echo NB_COMMITS=$(git rev-list $LAST_TAG..main --count) >> $GITHUB_OUTPUT
      - uses: andymckay/cancel-action@271cfbfa11ca9222f7be99a47e8f929574549e0a # 0.4
        if: steps.check.outputs.NB_COMMITS <= 1
      - name: Prepare
        id: prepare
        run: |
          pip install poetry
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          echo MINOR=$(date +%Y.%m) >> $GITHUB_ENV
      - name: Tag new version
        run: |
          git checkout -b release
          NEW_PATCH=$(git tag | grep $MINOR | wc -l)
          VERSION=${MINOR}.${NEW_PATCH}
          poetry version $VERSION
          git commit -am $VERSION
          git tag $VERSION
          git push --tags origin $VERSION
      - name: Commit new dev version
        run: |
          git checkout main
          NEW_PATCH=$(git tag | grep $MINOR | wc -l)
          VERSION=${MINOR}.${NEW_PATCH}-dev
          poetry version $VERSION
          git commit -am $VERSION
          git push origin main
