name: Calendar Versioning

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for new commits
        id: check
        run: |
          LAST_TAG=$(git tag --sort -v:refname | head -n1)
          echo NB_COMMITS=$(git rev-list $LAST_TAG..main --count) >> $GITHUB_OUTPUT
      - name: Prepare
        id: prepare
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          echo MINOR=$(date +%Y.%m) >> $GITHUB_ENV
      - name: Tag new version
        run: |
          git checkout -b release
          NEW_PATCH=$(git tag | grep $MINOR | wc -l)
          VERSION=${MINOR}.${NEW_PATCH}
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          git commit -am $VERSION
          git tag $VERSION
          git push --tags origin $VERSION
      - name: Commit new dev version
        run: |
          git checkout main
          NEW_PATCH=$(git tag | grep $MINOR | wc -l)
          VERSION=${MINOR}.${NEW_PATCH}-dev
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          git commit -am $VERSION
          git push origin main
